language: go

dist: focal
sudo: required

go: "1.17.13"

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      virt: vm
      group: edge
    - arch: amd64
      name: "amd64-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:329f5b7debacb58d6b80f5117d3922fc4dc35344@sha256:16fab750aed13351f568fc5abde2b378165358c789486e77563fd428fe172806
        - LOCKDEBUG=1

# Disabled due to a compilation issue: https://github.com/cilium/cilium/issues/13252
#    - arch: arm64-graviton2
#      name: "arm64-graviton2-race"
#      if: type != pull_request
#      env:
#        - RACE=1
#        - BASE_IMAGE=quay.io/cilium/cilium-runtime:329f5b7debacb58d6b80f5117d3922fc4dc35344@sha256:16fab750aed13351f568fc5abde2b378165358c789486e77563fd428fe172806
#        - LOCKDEBUG=1
#      virt: vm
#      group: edge

if: branch = master OR type = pull_request

addons:
  apt:
    packages:
      - kernel-package
      - gnupg
      - libncurses5

before_install: ./.travis/prepare.sh

before_script:
  - export PATH=/usr/local/clang/bin:$PATH

script: ./.travis/build.sh

notifications:
  email: false
